services:

  postgresql:
    image: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - 5432:5432
  nats:
    image: nats-streaming
    ports:
      - 4222:4222
  redis:
    image: redis
    ports:
      - 6379:6379

